<?php

namespace Ajgl\Doctrine\DBAL\Types;

use Doctrine\DBAL\Types\Type;
use Doctrine\Tests\DBAL\Mocks\MockPlatform;
use Doctrine\DBAL\Connection;

/**
 * Test class for IntegerArrayType.
 * Generated by PHPUnit on 2012-07-18 at 09:03:09.
 */
class IntegerArrayTypeTest
    extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MockPlatform
     */
    protected $platform;

    /**
     * @var IntegerArrayType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        if (!Type::hasType('int[]')) {
            Type::addType('int[]', 'Ajgl\Doctrine\DBAL\Types\IntegerArrayType');
        } else {
            Type::overrideType('int[]', 'Ajgl\Doctrine\DBAL\Types\IntegerArrayType');
        }
        $this->platform = new MockPlatform();
        $this->object = Type::getType('int[]');
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\IntegerArrayType::getSqlDeclaration
     */
    public function testGetSqlDeclaration()
    {
        $this->assertEquals('INTEGER[]', $this->object->getSqlDeclaration(array(), $this->platform));
        $this->assertEquals('INTEGER[5]', $this->object->getSqlDeclaration(array('length' => 5), $this->platform));
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\IntegerArrayType::convertToPHPValue
     */
    public function testConvertToPHPValue()
    {
        $expected = array(10000, 10000, 10000, 10000);
        $actual = $this->object->convertToPHPValue('{10000, 10000, 10000,10000}', $this->platform);
        $this->assertSame($expected, $actual);
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\IntegerArrayType::convertToDatabaseValue
     */
    public function testConvertToDatabaseValue()
    {
        $expected = '{10000,10000,10000,10000}';
        $actual = $this->object->convertToDatabaseValue(array(10000, 10000, 10000, 10000), $this->platform);
        $this->assertSame($expected, $actual);
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\IntegerArrayType::getName
     */
    public function testGetName()
    {
        $this->assertEquals(IntegerArrayType::INTEGERARRAY, $this->object->getName());
    }
}
