<?php

namespace Ajgl\Doctrine\DBAL\Types;

use Doctrine\DBAL\Types\Type;
use Doctrine\Tests\DBAL\Mocks\MockPlatform;

/**
 * Test class for IssnType.
 * Generated by PHPUnit on 2012-07-18 at 09:03:09.
 */
class IssnTypeTest
    extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MockPlatform
     */
    protected $platform;

    /**
     * @var IssnType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        if (!Type::hasType('issn')) {
            Type::addType('issn', 'Ajgl\Doctrine\DBAL\Types\IssnType');
        } else {
            Type::overrideType('issn', 'Ajgl\Doctrine\DBAL\Types\IssnType');
        }
        $this->platform = new MockPlatform();
        $this->object = Type::getType('issn');
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\IssnType::getSqlDeclaration
     */
    public function testGetSqlDeclaration()
    {
        $this->assertEquals('ISSN', $this->object->getSqlDeclaration(array(), $this->platform));
        $this->assertEquals('ISSN', $this->object->getSqlDeclaration(array('length' => 5), $this->platform));
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\IssnType::getName
     */
    public function testGetName()
    {
        $this->assertEquals(IssnType::ISSN, $this->object->getName());
    }
}
