<?php

namespace Ajgl\Doctrine\DBAL\Types;

use Doctrine\DBAL\Types\Type;
use PHPUnit\Framework\TestCase;

/**
 * Test class for BigIntArrayType.
 * Generated by PHPUnit on 2012-07-18 at 09:03:09.
 */
final class BigIntArrayTypeTest
    extends TestCase
{
    /**
     * @var BigIntArrayType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
         if (!Type::hasType('bigint[]')) {
            Type::addType('bigint[]', 'Ajgl\Doctrine\DBAL\Types\BigIntArrayType');
        } else {
            Type::overrideType('bigint[]', 'Ajgl\Doctrine\DBAL\Types\BigIntArrayType');
        }
        $this->object = Type::getType('bigint[]');
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\BigIntArrayType::getName
     */
    public function testGetName()
    {
        $this->assertEquals(BigIntArrayType::BIGINTARRAY, $this->object->getName());
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\BigIntArrayType::getInnerType
     */
    public function testGetInnerType()
    {
        $this->assertInstanceOf('Doctrine\DBAL\Types\BigIntType', $this->object->getInnerType());
    }

}
