<?php

declare(strict_types=1);

/*
 * AJGL Doctrine DBAL Types
 *
 * Copyright (C) Antonio J. García Lagar <aj@garcialagar.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Ajgl\Doctrine\DBAL\Types;

use Doctrine\DBAL\Types\Type;
use PHPUnit\Framework\TestCase;

/**
 * Test class for BigIntArrayType.
 * Generated by PHPUnit on 2012-07-18 at 09:03:09.
 */
final class BigIntArrayTypeTest extends TestCase
{
    /**
     * @var BigIntArrayType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        if (!Type::hasType('bigint[]')) {
            Type::addType('bigint[]', 'Ajgl\Doctrine\DBAL\Types\BigIntArrayType');
        } else {
            Type::overrideType('bigint[]', 'Ajgl\Doctrine\DBAL\Types\BigIntArrayType');
        }
        $this->object = Type::getType('bigint[]');
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\BigIntArrayType::getName
     */
    public function testGetName(): void
    {
        $this->assertEquals(BigIntArrayType::BIGINTARRAY, $this->object->getName());
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\BigIntArrayType::getInnerType
     */
    public function testGetInnerType(): void
    {
        $this->assertInstanceOf('Doctrine\DBAL\Types\BigIntType', $this->object->getInnerType());
    }

}
