<?php

declare(strict_types=1);

/*
 * AJGL Doctrine DBAL Types
 *
 * Copyright (C) Antonio J. García Lagar <aj@garcialagar.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Ajgl\Doctrine\DBAL\Types;

use Doctrine\DBAL\Types\Type;
use PHPUnit\Framework\TestCase;

/**
 * Test class for BooleanArrayType.
 * Generated by PHPUnit on 2012-07-18 at 09:03:09.
 */
final class BooleanArrayTypeTest extends TestCase
{
    /**
     * @var BooleanArrayType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        if (!Type::hasType('boolean[]')) {
            Type::addType('boolean[]', 'Ajgl\Doctrine\DBAL\Types\BooleanArrayType');
        } else {
            Type::overrideType('boolean[]', 'Ajgl\Doctrine\DBAL\Types\BooleanArrayType');
        }
        $this->object = Type::getType('boolean[]');
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\BooleanArrayType::getName
     */
    public function testGetName(): void
    {
        $this->assertEquals(BooleanArrayType::BOOLEANARRAY, $this->object->getName());
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\BooleanArrayType::getInnerType
     */
    public function testGetInnerType(): void
    {
        $this->assertInstanceOf('Doctrine\DBAL\Types\BooleanType', $this->object->getInnerType());
    }

}
