<?php

declare(strict_types=1);

/*
 * AJGL Doctrine DBAL Types
 *
 * Copyright (C) Antonio J. García Lagar <aj@garcialagar.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Ajgl\Doctrine\DBAL\Types;

use Doctrine\DBAL\Types\Type;
use PHPUnit\Framework\TestCase;

/**
 * Test class for IntegerArrayType.
 * Generated by PHPUnit on 2012-07-18 at 09:03:09.
 */
final class IntegerArrayTypeTest extends TestCase
{
    /**
     * @var IntegerArrayType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        if (!Type::hasType('integer[]')) {
            Type::addType('integer[]', 'Ajgl\Doctrine\DBAL\Types\IntegerArrayType');
        } else {
            Type::overrideType('integer[]', 'Ajgl\Doctrine\DBAL\Types\IntegerArrayType');
        }
        $this->object = Type::getType('integer[]');
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\IntegerArrayType::getName
     */
    public function testGetName(): void
    {
        $this->assertEquals(IntegerArrayType::INTEGERARRAY, $this->object->getName());
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\IntegerArrayType::getInnerType
     */
    public function testGetInnerType(): void
    {
        $this->assertInstanceOf('Doctrine\DBAL\Types\IntegerType', $this->object->getInnerType());
    }

}
