<?php

namespace Ajgl\Doctrine\DBAL\Types;

use Doctrine\DBAL\Types\Type;
use PHPUnit\Framework\TestCase;

/**
 * Test class for IntegerArrayType.
 * Generated by PHPUnit on 2012-07-18 at 09:03:09.
 */
class IntegerArrayTypeTest
    extends TestCase
{
    /**
     * @var IntegerArrayType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
         if (!Type::hasType('integer[]')) {
            Type::addType('integer[]', 'Ajgl\Doctrine\DBAL\Types\IntegerArrayType');
        } else {
            Type::overrideType('integer[]', 'Ajgl\Doctrine\DBAL\Types\IntegerArrayType');
        }
        $this->object = Type::getType('integer[]');
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\IntegerArrayType::getName
     */
    public function testGetName()
    {
        $this->assertEquals(IntegerArrayType::INTEGERARRAY, $this->object->getName());
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\IntegerArrayType::getInnerType
     */
    public function testGetInnerType()
    {
        $this->assertInstanceOf('Doctrine\DBAL\Types\IntegerType', $this->object->getInnerType());
    }

}
