<?php

declare(strict_types=1);

/*
 * AJGL Doctrine DBAL Types
 *
 * Copyright (C) Antonio J. García Lagar <aj@garcialagar.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Ajgl\Doctrine\DBAL\Types;

use Doctrine\DBAL\Types\Type;
use PHPUnit\Framework\TestCase;

/**
 * Test class for SmallIntArrayType.
 * Generated by PHPUnit on 2012-07-18 at 09:03:09.
 */
final class SmallIntArrayTypeTest extends TestCase
{
    /**
     * @var SmallIntArrayType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        if (!Type::hasType('smallint[]')) {
            Type::addType('smallint[]', 'Ajgl\Doctrine\DBAL\Types\SmallIntArrayType');
        } else {
            Type::overrideType('smallint[]', 'Ajgl\Doctrine\DBAL\Types\SmallIntArrayType');
        }
        $this->object = Type::getType('smallint[]');
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\SmallIntArrayType::getName
     */
    public function testGetName(): void
    {
        $this->assertEquals(SmallIntArrayType::SMALLINTARRAY, $this->object->getName());
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\SmallIntArrayType::getInnerType
     */
    public function testGetInnerType(): void
    {
        $this->assertInstanceOf('Doctrine\DBAL\Types\SmallIntType', $this->object->getInnerType());
    }

}
