<?php

namespace Ajgl\Doctrine\DBAL\Types;

use Doctrine\DBAL\Types\Type;
use PHPUnit\Framework\TestCase;

/**
 * Test class for SmallIntArrayType.
 * Generated by PHPUnit on 2012-07-18 at 09:03:09.
 */
class SmallIntArrayTypeTest
    extends TestCase
{
    /**
     * @var SmallIntArrayType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
         if (!Type::hasType('smallint[]')) {
            Type::addType('smallint[]', 'Ajgl\Doctrine\DBAL\Types\SmallIntArrayType');
        } else {
            Type::overrideType('smallint[]', 'Ajgl\Doctrine\DBAL\Types\SmallIntArrayType');
        }
        $this->object = Type::getType('smallint[]');
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\SmallIntArrayType::getName
     */
    public function testGetName()
    {
        $this->assertEquals(SmallIntArrayType::SMALLINTARRAY, $this->object->getName());
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\SmallIntArrayType::getInnerType
     */
    public function testGetInnerType()
    {
        $this->assertInstanceOf('Doctrine\DBAL\Types\SmallIntType', $this->object->getInnerType());
    }

}
