<?php

declare(strict_types=1);

/*
 * AJGL Doctrine DBAL Types
 *
 * Copyright (C) Antonio J. García Lagar <aj@garcialagar.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Ajgl\Doctrine\DBAL\Types;

use Doctrine\DBAL\Types\Type;
use PHPUnit\Framework\TestCase;

/**
 * Test class for StringArrayType.
 * Generated by PHPUnit on 2012-07-18 at 09:03:09.
 */
final class StringArrayTypeTest extends TestCase
{
    /**
     * @var StringArrayType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        if (!Type::hasType('string[]')) {
            Type::addType('string[]', 'Ajgl\Doctrine\DBAL\Types\StringArrayType');
        } else {
            Type::overrideType('string[]', 'Ajgl\Doctrine\DBAL\Types\StringArrayType');
        }
        $this->object = Type::getType('string[]');
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\StringArrayType::getName
     */
    public function testGetName(): void
    {
        $this->assertEquals(StringArrayType::STRINGARRAY, $this->object->getName());
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\StringArrayType::getInnerType
     */
    public function testGetInnerType(): void
    {
        $this->assertInstanceOf('Doctrine\DBAL\Types\StringType', $this->object->getInnerType());
    }

}
