<?php

declare(strict_types=1);

/*
 * AJGL Doctrine DBAL Types
 *
 * Copyright (C) Antonio J. García Lagar <aj@garcialagar.es>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Ajgl\Doctrine\DBAL\Types;

use Doctrine\DBAL\Types\Type;
use PHPUnit\Framework\TestCase;

/**
 * Test class for TextArrayType.
 * Generated by PHPUnit on 2012-07-18 at 09:03:09.
 */
final class TextArrayTypeTest extends TestCase
{
    /**
     * @var TextArrayType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        if (!Type::hasType('text[]')) {
            Type::addType('text[]', 'Ajgl\Doctrine\DBAL\Types\TextArrayType');
        } else {
            Type::overrideType('text[]', 'Ajgl\Doctrine\DBAL\Types\TextArrayType');
        }
        $this->object = Type::getType('text[]');
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\TextArrayType::getName
     */
    public function testGetName(): void
    {
        $this->assertEquals(TextArrayType::TEXTARRAY, $this->object->getName());
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\TextArrayType::getInnerType
     */
    public function testGetInnerType(): void
    {
        $this->assertInstanceOf('Doctrine\DBAL\Types\TextType', $this->object->getInnerType());
    }

}
