<?php

namespace Ajgl\Doctrine\DBAL\Types;

use Doctrine\DBAL\Types\Type;
use PHPUnit\Framework\TestCase;

/**
 * Test class for TextArrayType.
 * Generated by PHPUnit on 2012-07-18 at 09:03:09.
 */
class TextArrayTypeTest
    extends TestCase
{
    /**
     * @var TextArrayType
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
         if (!Type::hasType('text[]')) {
            Type::addType('text[]', 'Ajgl\Doctrine\DBAL\Types\TextArrayType');
        } else {
            Type::overrideType('text[]', 'Ajgl\Doctrine\DBAL\Types\TextArrayType');
        }
        $this->object = Type::getType('text[]');
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\TextArrayType::getName
     */
    public function testGetName()
    {
        $this->assertEquals(TextArrayType::TEXTARRAY, $this->object->getName());
    }

    /**
     * @covers Ajgl\Doctrine\DBAL\Types\TextArrayType::getInnerType
     */
    public function testGetInnerType()
    {
        $this->assertInstanceOf('Doctrine\DBAL\Types\TextType', $this->object->getInnerType());
    }

}
